INSERT INTO invitados (invitado_de, familia, nombre, slug) VALUES
('lilian',1,'FAM. FERRER HERNANDEZ', 'fam-ferrer-hernandez'),
('lilian',0,'SRA. REYNA MORAN', 'sra-reyna-moran'),
('lilian',1,'FAM. HERNANDEZ MARTINEZ', 'fam-hernandez-martinez'),
('lilian',1,'FAM. TELLES HERNANDEZ', 'fam-telles-hernandez'),
('lilian',1,'SRA. MARINA MORAN Y FAMILIA', 'sra-marina-moran-y-familia'),
('lilian',1,'FAM. HERNANDEZ BARRERA', 'fam-hernandez-barrera'),
('lilian',0,'SRTA. LETICIA DAMIAN', 'srta-leticia-damian'),
('lilian',0,'SRTA. ARACELI CRUZ', 'srta-araceli-cruz'),
('lilian',0,'SRA. JUANA MARTINEZ', 'sra-juana-martinez'),
('lilian',1,'FAM. VARGAS AMBROSIO', 'fam-vargas-ambrosio'),
('lilian',0,'SRTA. JUANA OLVERA', 'srta-juana-olvera'),
('lilian',1,'FAM. ORTEGA DAVILA', 'fam-ortega-davila'),
('lilian',0,'SRTA. YOJAIRA', 'srta-yojaira'),
('lilian',0,'SR. MARCO MONJARAS', 'sr-marco-monjaras'),
('lilian',1,'FAM. GONZALEZ APELLANIZ', 'fam-gonzalez-apellaniz'),
('lilian',0,'SR. IVAN MARQUEZ', 'sr-ivan-marquez'),
('lilian',0,'SR. CESAR GARCIA', 'sr-cesar-garcia'),
('lilian',0,'SRTA. ESMERALDA LOPEZ', 'srta-esmeralda-lopez'),
('lilian',0,'PADRE CAMBRON', 'padre-cambron'),
('lilian',1,'FAM. RUIZ GARCIA', 'fam-ruiz-garcia'),
('lilian',0,'SRTA. ANA MARIA', 'srta-ana-maria');